### PR TITLE
Update Collections.php

### PR DESCRIPTION
**Pull request by yaroslavpopovic**
Added exists method

### CODE REVIEW

**Comment by hkulekci** [comment]
Hello @yaroslavpopovic thank you for contributing. Sorry for late response. I am in a vacation. Just checked the PR and could you please add an integration test for the exists endpoint?

**Comment by yaroslavpopovic** [comment]
yes! sure!

**Comment by hkulekci** [comment]
Thank you! Let me run the tests. 🙌

**Comment by hkulekci** [comment]
Ohh yes. Sorry. Let me do it.

**Comment by hkulekci** [comment]
https://github.com/hkulekci/qdrant-php/releases/tag/v0.5.5 here it is a new release for this PR. Thanks for contributing ❤️

**Pull request merged**
