### PR TITLE
Use php feature constructor property promotion

### PR DESCRIPTION
**Pull request by NiCr42**

### CODE REVIEW

**Comment by hkulekci** [comment]
Hey @NiCr42 thanks for contributing. I rerun the pipeline. Lets see. We can merge if it pass.

**Comment by hkulekci** [comment]
Hey @NiCr42, we did not have a test for the Point class. So, for this reason, whenever you change that class coverage, expect a unit test for it. Could you please add the following test to your branch?

Need to be created as `tests/Unit/Models/Request/PointTest.php`

```
<?php
/**
 * @since     Mar 2023
 * @author    Haydar KULEKCI <haydarkulekci@gmail.com>
 */

namespace Qdrant\Tests\Unit\Models\Request;

use PHPUnit\Framework\TestCase;
use Qdrant\Models\Request\Point;
use Qdrant\Models\VectorStruct;

class PointTest extends TestCase
{
    public function testValidBasic(): void
    {
        $point = new Point(
            '1',
            new VectorStruct([1, 2, 3])
        );

        $this->assertEquals([
            'id' => '1',
            'vector' => [1, 2, 3]
        ], $point->toArray());
    }

    public function testValidBasicWithArrayVector(): void
    {
        $point = new Point(
            '1',
            [1, 2, 3]
        );

        $this->assertEquals([
            'id' => '1',
            'vector' => [1, 2, 3]
        ], $point->toArray());
    }

    public function testValidBasicWithPayload(): void
    {
        $point = new Point(
            '1',
            [1, 2, 3],
            ['foo' => 'bar']
        );

        $this->assertEquals([
            'id' => '1',
            'vector' => [1, 2, 3],
            'payload' => ['foo' => 'bar']
        ], $point->toArray());
    }
}
```

**Comment by hkulekci** [comment]
Other than this, LGTM. Thanks again. I've wanted to do this for a long time but could not find a chance.

**Comment by NiCr42** [comment]
Hello @hkulekci.
It's done.

**Pull request merged**
