### PR TITLE
Added `score_threshold` support

### PR DESCRIPTION
**Pull request by gregpriday**
Fairly straightforward. Qdrant allows you to specify a `score_threshold` for search requests and recommended requests.

https://qdrant.tech/documentation/concepts/search/#filtering-results-by-score

### CODE REVIEW

**Comment by gregpriday** [comment]
I'll add a test for this later today too.

**Comment by hkulekci** [comment]
Lgtm. Just that would be great if we add tests. Thanks ✌️

**Comment by gregpriday** [comment]
@hkulekci Test added 🚀

**Comment by gregpriday** [comment]
I added tests for threshold in recommended to improve this PR's Codecov, but it's not showing up here https://github.com/gregpriday/qdrant-php/tree/feature/threshold-support

**Comment by hkulekci** [comment]
I guess, this is done too. Thanks ✌️

**Pull request merged**
