### PR TITLE
Add `withPayload` and `withVector` properties on `RecommendRequest` class

### PR DESCRIPTION
**Pull request by julien-jourde**
Hey,
A little update on `RecommendedRequest` class to add missing `withPayload` and `withVector` properties.

### CODE REVIEW

**Comment by hkulekci** [comment]
Thank you, @julien-jourde, for contributing.

**Comment by julien-jourde** [comment]
You're welcome!
Could you create a new release when this one will be merged?

**Comment by hkulekci** [comment]
Done! https://github.com/hkulekci/qdrant-php/releases/tag/v0.5.7 ✌️

**Comment by julien-jourde** [comment]
Fast guy ! :running:

**Pull request merged**
